/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'difficulty' : Difficulty,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CandidateProfile = IDL.Record({
  'experienceLevel' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'targetRole' : IDL.Text,
});
export const Time = IDL.Int;
export const InterviewStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'evaluated' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const InterviewSession = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Opt(Time),
  'status' : InterviewStatus,
  'evaluator' : IDL.Principal,
  'overallScore' : IDL.Opt(IDL.Nat),
  'endTime' : IDL.Opt(Time),
  'feedback' : IDL.Opt(IDL.Text),
  'timeLimitMinutes' : IDL.Nat,
  'flagNote' : IDL.Opt(IDL.Text),
  'questionIds' : IDL.Vec(IDL.Nat),
  'candidate' : IDL.Principal,
  'flagged' : IDL.Bool,
});
export const AnswerSubmission = IDL.Record({
  'feedback' : IDL.Opt(IDL.Text),
  'score' : IDL.Opt(IDL.Nat),
  'timeTakenSeconds' : IDL.Nat,
  'questionId' : IDL.Nat,
  'answerText' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOverallAssessment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'addQuestion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Difficulty, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimFirstAdmin' : IDL.Func([], [], []),
  'createCandidateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createInterviewSession' : IDL.Func(
      [IDL.Principal, IDL.Vec(IDL.Nat), IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createMockInterview' : IDL.Func([IDL.Vec(IDL.Nat), IDL.Nat], [IDL.Nat], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'flagSession' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidateProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CandidateProfile)],
      ['query'],
    ),
  'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(InterviewSession)], ['query']),
  'getSessionAnswers' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AnswerSubmission)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'scoreAnswer' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'scoreMockAnswer' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'selfRegisterAsUser' : IDL.Func([], [], []),
  'startSession' : IDL.Func([IDL.Nat], [], []),
  'submitAnswer' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'submitSession' : IDL.Func([IDL.Nat], [], []),
  'updateQuestion' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Difficulty, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'difficulty' : Difficulty,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CandidateProfile = IDL.Record({
    'experienceLevel' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'targetRole' : IDL.Text,
  });
  const Time = IDL.Int;
  const InterviewStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'evaluated' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const InterviewSession = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Opt(Time),
    'status' : InterviewStatus,
    'evaluator' : IDL.Principal,
    'overallScore' : IDL.Opt(IDL.Nat),
    'endTime' : IDL.Opt(Time),
    'feedback' : IDL.Opt(IDL.Text),
    'timeLimitMinutes' : IDL.Nat,
    'flagNote' : IDL.Opt(IDL.Text),
    'questionIds' : IDL.Vec(IDL.Nat),
    'candidate' : IDL.Principal,
    'flagged' : IDL.Bool,
  });
  const AnswerSubmission = IDL.Record({
    'feedback' : IDL.Opt(IDL.Text),
    'score' : IDL.Opt(IDL.Nat),
    'timeTakenSeconds' : IDL.Nat,
    'questionId' : IDL.Nat,
    'answerText' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOverallAssessment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'addQuestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Difficulty, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimFirstAdmin' : IDL.Func([], [], []),
    'createCandidateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createInterviewSession' : IDL.Func(
        [IDL.Principal, IDL.Vec(IDL.Nat), IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createMockInterview' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'flagSession' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidateProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CandidateProfile)],
        ['query'],
      ),
    'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(InterviewSession)], ['query']),
    'getSessionAnswers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AnswerSubmission)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'scoreAnswer' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'scoreMockAnswer' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'selfRegisterAsUser' : IDL.Func([], [], []),
    'startSession' : IDL.Func([IDL.Nat], [], []),
    'submitAnswer' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'submitSession' : IDL.Func([IDL.Nat], [], []),
    'updateQuestion' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Difficulty, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };