/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnswerSubmission {
  'feedback' : [] | [string],
  'score' : [] | [bigint],
  'timeTakenSeconds' : bigint,
  'questionId' : bigint,
  'answerText' : string,
}
export interface CandidateProfile {
  'experienceLevel' : string,
  'name' : string,
  'email' : string,
  'resumeText' : string,
  'extractedSkills' : Array<string>,
  'targetRole' : string,
}
export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface InterviewSession {
  'id' : bigint,
  'startTime' : [] | [Time],
  'status' : InterviewStatus,
  'evaluator' : Principal,
  'overallScore' : [] | [bigint],
  'endTime' : [] | [Time],
  'feedback' : [] | [string],
  'timeLimitMinutes' : bigint,
  'flagNote' : [] | [string],
  'questionIds' : Array<bigint>,
  'candidate' : Principal,
  'flagged' : boolean,
}
export type InterviewStatus = { 'scheduled' : null } |
  { 'evaluated' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface Question {
  'id' : bigint,
  'title' : string,
  'difficulty' : Difficulty,
  'tags' : Array<string>,
  'description' : string,
  'category' : string,
}
export interface SkillsAndResume {
  'resumeText' : string,
  'skills' : Array<string>,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOverallAssessment' : ActorMethod<[bigint, bigint, string], undefined>,
  'addQuestion' : ActorMethod<
    [string, string, string, Difficulty, Array<string>],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimFirstAdmin' : ActorMethod<[], undefined>,
  'createCandidateProfile' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'createInterviewSession' : ActorMethod<
    [Principal, Array<bigint>, bigint],
    bigint
  >,
  'createMockInterview' : ActorMethod<[Array<bigint>, bigint], bigint>,
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  'flagSession' : ActorMethod<[bigint, string], undefined>,
  'getAdminAssigned' : ActorMethod<[], boolean>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidateProfile' : ActorMethod<[Principal], [] | [CandidateProfile]>,
  'getFilteredQuestions' : ActorMethod<
    [[] | [string], [] | [Difficulty], [] | [string]],
    Array<Question>
  >,
  'getResumeSkills' : ActorMethod<[Principal], [] | [SkillsAndResume]>,
  'getResumeSkillsDeprecated' : ActorMethod<
    [Principal],
    [Array<string>, string]
  >,
  'getSession' : ActorMethod<[bigint], [] | [InterviewSession]>,
  'getSessionAnswers' : ActorMethod<[bigint], Array<AnswerSubmission>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveResumeSkills' : ActorMethod<[Array<string>, string], undefined>,
  'scoreAnswer' : ActorMethod<[bigint, bigint, bigint, string], undefined>,
  'scoreMockAnswer' : ActorMethod<[bigint, bigint, bigint, string], undefined>,
  'selfRegisterAsUser' : ActorMethod<[], undefined>,
  'startSession' : ActorMethod<[bigint], undefined>,
  'submitAnswer' : ActorMethod<[bigint, bigint, string, bigint], undefined>,
  'submitSession' : ActorMethod<[bigint], undefined>,
  'updateQuestion' : ActorMethod<
    [bigint, string, string, string, Difficulty, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];