/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface SkillsAndResume {
    resumeText: string;
    skills: Array<string>;
}
export interface AnswerSubmission {
    feedback?: string;
    score?: bigint;
    timeTakenSeconds: bigint;
    questionId: bigint;
    answerText: string;
}
export interface InterviewSession {
    id: bigint;
    startTime?: Time;
    status: InterviewStatus;
    evaluator: Principal;
    overallScore?: bigint;
    endTime?: Time;
    feedback?: string;
    timeLimitMinutes: bigint;
    flagNote?: string;
    questionIds: Array<bigint>;
    candidate: Principal;
    flagged: boolean;
}
export interface CandidateProfile {
    experienceLevel: string;
    name: string;
    email: string;
    resumeText: string;
    extractedSkills: Array<string>;
    targetRole: string;
}
export interface Question {
    id: bigint;
    title: string;
    difficulty: Difficulty;
    tags: Array<string>;
    description: string;
    category: string;
}
export interface UserProfile {
    name: string;
}
export enum Difficulty {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export enum InterviewStatus {
    scheduled = "scheduled",
    evaluated = "evaluated",
    completed = "completed",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOverallAssessment(sessionId: bigint, overallScore: bigint, feedback: string): Promise<void>;
    addQuestion(title: string, description: string, category: string, difficulty: Difficulty, tags: Array<string>): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimFirstAdmin(): Promise<void>;
    createCandidateProfile(name: string, email: string, targetRole: string, experienceLevel: string): Promise<void>;
    createInterviewSession(candidate: Principal, questionIds: Array<bigint>, timeLimitMinutes: bigint): Promise<bigint>;
    createMockInterview(questionIds: Array<bigint>, timeLimitMinutes: bigint): Promise<bigint>;
    deleteQuestion(id: bigint): Promise<void>;
    flagSession(sessionId: bigint, note: string): Promise<void>;
    getAdminAssigned(): Promise<boolean>;
    getAllQuestions(): Promise<Array<Question>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCandidateProfile(candidate: Principal): Promise<CandidateProfile | null>;
    getFilteredQuestions(category: string | null, difficulty: Difficulty | null, search: string | null): Promise<Array<Question>>;
    getResumeSkills(candidate: Principal): Promise<SkillsAndResume | null>;
    getResumeSkillsDeprecated(candidate: Principal): Promise<[Array<string>, string]>;
    getSession(sessionId: bigint): Promise<InterviewSession | null>;
    getSessionAnswers(sessionId: bigint): Promise<Array<AnswerSubmission>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveResumeSkills(skills: Array<string>, resumeText: string): Promise<void>;
    scoreAnswer(sessionId: bigint, questionId: bigint, score: bigint, feedback: string): Promise<void>;
    scoreMockAnswer(sessionId: bigint, questionId: bigint, score: bigint, feedback: string): Promise<void>;
    selfRegisterAsUser(): Promise<void>;
    startSession(sessionId: bigint): Promise<void>;
    submitAnswer(sessionId: bigint, questionId: bigint, answerText: string, timeTakenSeconds: bigint): Promise<void>;
    submitSession(sessionId: bigint): Promise<void>;
    updateQuestion(id: bigint, title: string, description: string, category: string, difficulty: Difficulty, tags: Array<string>): Promise<void>;
}
import type { AnswerSubmission as _AnswerSubmission, CandidateProfile as _CandidateProfile, Difficulty as _Difficulty, InterviewSession as _InterviewSession, InterviewStatus as _InterviewStatus, Question as _Question, SkillsAndResume as _SkillsAndResume, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOverallAssessment(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOverallAssessment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOverallAssessment(arg0, arg1, arg2);
            return result;
        }
    }
    async addQuestion(arg0: string, arg1: string, arg2: string, arg3: Difficulty, arg4: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(arg0, arg1, arg2, to_candid_Difficulty_n1(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(arg0, arg1, arg2, to_candid_Difficulty_n1(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimFirstAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimFirstAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimFirstAdmin();
            return result;
        }
    }
    async createCandidateProfile(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCandidateProfile(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCandidateProfile(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createInterviewSession(arg0: Principal, arg1: Array<bigint>, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInterviewSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInterviewSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createMockInterview(arg0: Array<bigint>, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMockInterview(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMockInterview(arg0, arg1);
            return result;
        }
    }
    async deleteQuestion(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuestion(arg0);
            return result;
        }
    }
    async flagSession(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.flagSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flagSession(arg0, arg1);
            return result;
        }
    }
    async getAdminAssigned(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAssigned();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAssigned();
            return result;
        }
    }
    async getAllQuestions(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuestions();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuestions();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidateProfile(arg0: Principal): Promise<CandidateProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidateProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidateProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredQuestions(arg0: string | null, arg1: Difficulty | null, arg2: string | null): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredQuestions(to_candid_opt_n14(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredQuestions(to_candid_opt_n14(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResumeSkills(arg0: Principal): Promise<SkillsAndResume | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResumeSkills(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResumeSkills(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResumeSkillsDeprecated(arg0: Principal): Promise<[Array<string>, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.getResumeSkillsDeprecated(arg0);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResumeSkillsDeprecated(arg0);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getSession(arg0: bigint): Promise<InterviewSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionAnswers(arg0: bigint): Promise<Array<AnswerSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionAnswers(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionAnswers(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveResumeSkills(arg0: Array<string>, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveResumeSkills(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveResumeSkills(arg0, arg1);
            return result;
        }
    }
    async scoreAnswer(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.scoreAnswer(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scoreAnswer(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async scoreMockAnswer(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.scoreMockAnswer(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scoreMockAnswer(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async selfRegisterAsUser(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.selfRegisterAsUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selfRegisterAsUser();
            return result;
        }
    }
    async startSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startSession(arg0);
            return result;
        }
    }
    async submitAnswer(arg0: bigint, arg1: bigint, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAnswer(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAnswer(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSession(arg0);
            return result;
        }
    }
    async updateQuestion(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Difficulty, arg5: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuestion(arg0, arg1, arg2, arg3, to_candid_Difficulty_n1(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuestion(arg0, arg1, arg2, arg3, to_candid_Difficulty_n1(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
}
function from_candid_AnswerSubmission_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnswerSubmission): AnswerSubmission {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_InterviewSession_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterviewSession): InterviewSession {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_InterviewStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterviewStatus): InterviewStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CandidateProfile]): CandidateProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SkillsAndResume]): SkillsAndResume | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InterviewSession]): InterviewSession | null {
    return value.length === 0 ? null : from_candid_InterviewSession_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: [] | [_Time];
    status: _InterviewStatus;
    evaluator: Principal;
    overallScore: [] | [bigint];
    endTime: [] | [_Time];
    feedback: [] | [string];
    timeLimitMinutes: bigint;
    flagNote: [] | [string];
    questionIds: Array<bigint>;
    candidate: Principal;
    flagged: boolean;
}): {
    id: bigint;
    startTime?: Time;
    status: InterviewStatus;
    evaluator: Principal;
    overallScore?: bigint;
    endTime?: Time;
    feedback?: string;
    timeLimitMinutes: bigint;
    flagNote?: string;
    questionIds: Array<bigint>;
    candidate: Principal;
    flagged: boolean;
} {
    return {
        id: value.id,
        startTime: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.startTime)),
        status: from_candid_InterviewStatus_n21(_uploadFile, _downloadFile, value.status),
        evaluator: value.evaluator,
        overallScore: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.overallScore)),
        endTime: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.endTime)),
        feedback: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.feedback)),
        timeLimitMinutes: value.timeLimitMinutes,
        flagNote: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.flagNote)),
        questionIds: value.questionIds,
        candidate: value.candidate,
        flagged: value.flagged
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    feedback: [] | [string];
    score: [] | [bigint];
    timeTakenSeconds: bigint;
    questionId: bigint;
    answerText: string;
}): {
    feedback?: string;
    score?: bigint;
    timeTakenSeconds: bigint;
    questionId: bigint;
    answerText: string;
} {
    return {
        feedback: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.feedback)),
        score: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.score)),
        timeTakenSeconds: value.timeTakenSeconds,
        questionId: value.questionId,
        answerText: value.answerText
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    difficulty: _Difficulty;
    tags: Array<string>;
    description: string;
    category: string;
}): {
    id: bigint;
    title: string;
    difficulty: Difficulty;
    tags: Array<string>;
    description: string;
    category: string;
} {
    return {
        id: value.id,
        title: value.title,
        difficulty: from_candid_Difficulty_n8(_uploadFile, _downloadFile, value.difficulty),
        tags: value.tags,
        description: value.description,
        category: value.category
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    evaluated: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): InterviewStatus {
    return "scheduled" in value ? InterviewStatus.scheduled : "evaluated" in value ? InterviewStatus.evaluated : "completed" in value ? InterviewStatus.completed : "inProgress" in value ? InterviewStatus.inProgress : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): Difficulty {
    return "easy" in value ? Difficulty.easy : "hard" in value ? Difficulty.hard : "medium" in value ? Difficulty.medium : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnswerSubmission>): Array<AnswerSubmission> {
    return value.map((x)=>from_candid_AnswerSubmission_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Difficulty_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty | null): [] | [_Difficulty] {
    return value === null ? candid_none() : candid_some(to_candid_Difficulty_n1(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == Difficulty.easy ? {
        easy: null
    } : value == Difficulty.hard ? {
        hard: null
    } : value == Difficulty.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
